### PR TITLE
updated langs for en_GB, fully translated as many strings as possible…

### PR DESCRIPTION
**Pull request by aljawaid**
… for module

- en_GB updated
- added language string for custom filename part
- fully translated module-specific strings in module where possible
- added/converted language strings in non-EN language files

### CODE REVIEW

**Comment by caos30** [comment]
Hi @aljawaid, many thanks for your improvements on translations. I've been working also today on the other issues you wrote 2 days ago, and i will commit the my changes tomorrow (sorry, i'm very tired just now). In fact, i added some other minor improvements (more tootltips, for example ;-)

About your idea to use more "module-specific" translated texts, i agree with you that it's "safer". 

I only disagree with you about some translations you did for some labels... in a very few (maybe 2 cases) you didn't understood the final sense of the original text. But not worry, all the other translations are really great!!

Let me push tomorrow my changes, and then afterwards pull your request and adjust those few labels not well trabslated by you (in the correct way i mean, because certainly my english is not quite good grammatically talking, hehehe).

Cheers!
Sergi

**Comment by aljawaid** [comment]
Great, I very much look forward to it.  Please me mindful I used Google for the non-English translations.  However, I appreciate some of my translations may be incorrect though and your guidance on understanding would be very helpful.

**Comment by aljawaid** [comment]
@caos30 hello, any update?

**Comment by aljawaid** [comment]
@caos30 any update?  Looking forward to trying out the updated version

**Comment by caos30** [comment]
@aljawaid today i've been analyzing on detail your translations. First, i fixed catalan and castillian translations (i'm native of both). And afterwards i reviewed the english (en_GB) file. Before to continue, i would like to share with you my doubts regarding a couple of texts. I fully agree your cooperation, and i must apologize about not be able to answer before, i'm very sorry.
---------------------------------------------------------------------------------------
== SHIPPER

i don't have very clear what to put but i think that your translation doesn't mean the exact sense in this environment:

ME:  stocktransfersShipper=Shipper
YOU: stocktransfersShipper=Person Responsible

for me, "shipper" is the person who drive the truck carrying the stock from a depot to another depot. "Responsible" is not very clear... there are really 3 responsible person here: twho deliver stock on origin depot, the driver or transporter who carry the cargo, and the person who receive the cargo on destination depot. Do you understand me? for this reason, all them must sign the printed PDF. Said this, do you continue thinking that "shipper" is not correct? may be "driver"?

Indeed, this "shipper" is the name of just the same person who sign at bottom as "carried by". I suppose that depending on each customer of us, maybe in the top (shipper) we could be put the name of the shipping company, while at bottom would sign the driver. For this reason i initially choosed "shipper".

== PACKS/BOXES

For this other text, the value to show in this document is the number of "boxes" to carry and to deliver in the destination. It probably each box contain several items of several kind of articles, or not. But the printed PDF must contain the number of "packs" or "boxes" to be received. Please tell me what do you think is the best expression for that.

ME:  stocktransfersNPackages=Number of packs
YOU: stocktransfersNPackages=N° of Items

== DISPATCHED/DELIVERED

This is not correct, i think you got confused:

ME:  stocktransfersPDF8=Dispatched by
YOU: stocktransfersPDF8=Requested by

I tried to mark the person who DELIVER the stock tra be moved to the destination location. Maybe it could say "Delivered by", if you think that is better choice. 

== ABUSE OF UPPERCASE

I have doubts about if it is correct to use capital letters to each word in a text (titles/buttons), like this:

purchasesMenuTitle3=Stock Transfers List
WarehouseSource=Source Location
WarehouseTarget=Target Location
STLabelMovement=Stock Movement

A customer of mine, several years ago, born in England told me that this is not correct. Well, he was the boss and owner of his company (i did his website for ecommerce). 

This habit of use capital letters on each word is typical on american english (USA), but it really on Englad is not well seen, i think. Please, tell me your opinion or ask more people, before to update the english translation files.

**Comment by aljawaid** [comment]
_@caos30 Thanks for the explanantion.  I can only translate by the language string and guessing the function so most times I could get the purpose wrong :)_

### **SHIPPER**
`Driver` would make more sense after your explanantion.

### **PACKS/BOXES**
`N° of Items` would make more sense and be more universal.  For example, for me, I would measure packs/boxes/cartons/pieces so the translation of `N° of Items` for me would mean the quantities of items _**whether or not**_ it was a pack or a box or a carton etc.

### **DISPATCHED/DELIVERED**
`Delivered by` would be fine although anybody could change this to anything for their own set up.

### **ABUSE OF UPPERCASE**
I fully understand you but uppercase is not being abused.  More so, since ala Google, GitHub and Apple, lowercase is fully abused! hahaha

Title case is relevant and correct here as the titles and button texts are all titles.  So in correct English, the 'and' 'or' 'of' etc are not capitalised but each other word should be.

> A customer of mine, several years ago, born in England told me that this is not correct. Well, he was the boss and owner of his company (i did his website for ecommerce).
- I don't agree.  Buttons and headings should be all `Title Case` and not `Sentence case`.  The other benefit of Title Case is that it is easier on the eye to read and understand the layout of the screen.

I have pushed an update with these changes.  Let us know what you think.  I will test out v1.5 in the meantime on v7.0.3

**Comment by caos30** [comment]
Thanks for your work @aljawaid , i pulled just now your commits to the main repo ;)

**Pull request merged**
